// <auto-generated />
namespace HousesForRent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class leaserlocaton : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(leaserlocaton));
        
        string IMigrationMetadata.Id
        {
            get { return "201912200008315_leaserlocaton"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
