// <auto-generated />
namespace HousesForRent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class locationId001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(locationId001));
        
        string IMigrationMetadata.Id
        {
            get { return "202001011554251_locationId001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
