// <auto-generated />
namespace HousesForRent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class location005 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(location005));
        
        string IMigrationMetadata.Id
        {
            get { return "202001141318044_location005"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
