// <auto-generated />
namespace HousesForRent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addLocation002 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addLocation002));
        
        string IMigrationMetadata.Id
        {
            get { return "202001132248505_addLocation002"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
